# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='task',
        ),
    ]
